### ISSUE TITLE
visualizer image required

### ISSUE THREAD

**Issue by mz-bmcqueen** [sunayu/saltconf2017#1]
The demo sls pulls in an image called visualizer.  What is the visualizer? I don't see it in this repo.  Can you add it?

**Comment by mz-bmcqueen** [comment]
this thing I guess:  https://hub.docker.com/r/dockersamples/visualizer/

**Comment by justin-sunayu** [comment]
Yes thats it! I just pushed all those demo containers to a local repo for speed.
